# Generated by Django 3.1.2 on 2020-10-20 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha3', models.CharField(max_length=64)),
                ('charter', models.CharField(max_length=100)),
                ('difficulty_index', models.PositiveSmallIntegerField()),
                ('difficulty_shortname', models.CharField(max_length=8)),
                ('difficulty_name', models.CharField(max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.song')),
            ],
        ),
    ]
