# Generated by Django 3.1.2 on 2020-10-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_score', models.PositiveIntegerField()),
                ('judgements', models.JSONField()),
                ('max_chain', models.PositiveIntegerField()),
                ('gauge', models.PositiveIntegerField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.chart')),
            ],
        ),
    ]
