# Generated by Django 3.1.2 on 2020-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20201022_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='song_artist',
            field=models.CharField(db_column='song_artist', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(db_column='song_title', max_length=100),
        ),
    ]
