# Generated by Django 3.1.2 on 2020-10-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20201023_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
    ]
