# Generated by Django 3.1.2 on 2020-10-26 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0008_auto_20201023_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialscore',
            name='chart_sha3',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialscore',
            name='display_score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialscore',
            name='gauge',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialscore',
            name='judgements',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialscore',
            name='max_chain',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialscore',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialscore',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
